In [1]:
#Menyiapkan liblary yang dibutuhkan
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Menyiapkan data yang dipakai
df = pd.read_excel('Documents/Portofolio/Data Science/klasifikasi mutu padi/Dataset/Data Mutu Padi Organik.xls', header= 2).dropna()
df.head()

No.     Variates   P.   B.  Warna          rasa        teknik  Musim  \
1  1.0  panda wangi  6.3  1.2  putih  sangat pulen  Jajar Legowo  Hujan   
2  2.0      ciheran  7.2  2.3  putih         pulen  Jajar Legowo  Hujan   
3  3.0    mi kongga  6.1  3.3  putih  sangat pulen           SRI  Hujan   
4  4.0        IR 64  6.1  4.2  putih         pulen           SRI  Hujan   
5  5.0  Beras Merah  7.3  5.1  merah  sangat pulen  Jajar Legowo  Hujan   

           Penyakit   PH Grade Mutu  
1            Burung  2.0    Grade D  
2  penggerek batang  2.0    Grade C  
3     wereng coklat  2.0    Grade D  
4      wereng hijau  2.0    Grade B  
5             tikus  2.0    Grade C

In [3]:
#Menginisiliasi data karena masih menggunakan string
df = df.apply(lambda x: pd.factorize(x)[0])
df.drop(df.columns[[0]], axis =1 , inplace = True)
df.head()

Variates  P.  B.  Warna  rasa  teknik  Musim  Penyakit  PH  Grade Mutu
1         0   0   0      0     0       0      0         0   0           0
2         1   1   1      0     1       0      0         1   0           1
3         2   2   2      0     0       1      0         2   0           0
4         3   2   3      0     1       1      0         3   0           2
5         4   3   4      1     0       0      0         4   0           1

In [4]:
#memisahkan atribut dan juga labelnya
features = df.iloc[:,:-1].values
target = df.iloc[:,-1].values

In [5]:
#Membagi data training dan juga data testing
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test= train_test_split(features, target , test_size=0.25, random_state=0)


In [7]:
print("Data atribut training:")
print(x_train)
print("Data atribut testing:")
print(x_test)
print("Data target training:")
print(y_train)
print("Data target testing:")
print(y_test)

Data atribut training:
[[ 1  1  7 ...  0  2  0]
 [ 3  5  3 ...  1  4  1]
 [ 4  3 15 ...  0  2  0]
 ...
 [ 3  7  3 ...  1  3  3]
 [ 3  5  3 ...  0  2  2]
 [ 2  8 12 ...  1  2  3]]
Data atribut testing:
[[ 2  6  2 ...  0  3  2]
 [ 4  3  4 ...  1  3  1]
 [ 3  4  8 ...  0  3  0]
 ...
 [ 2  7  2 ...  1  0  3]
 [ 1  3 11 ...  0  2  2]
 [ 4  8  0 ...  0  2  2]]
Data target training:
[1 0 1 ... 2 1 1]
Data target testing:
[2 2 2 ... 1 2 2]


In [8]:
#melakukan pemodelan menggunakan algoritma C4.5
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
model=tree.DecisionTreeClassifier(random_state=0, max_depth=None, min_samples_split=2, min_samples_leaf=1,min_weight_fraction_leaf=0,max_leaf_nodes=None,min_impurity_decrease=0)
clf = model.fit(x_train, y_train)

In [9]:
#confution matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score 

In [10]:
y_pred = model.predict(x_test)
cm =confusion_matrix(y_test,y_pred)
print("confusion matrix")
print(cm)
akurasi=classification_report(y_test,y_pred)
print("tingkat akurasi algoritma C4.5")
print("Akurasi :", akurasi)
akurasi=accuracy_score(y_test,y_pred) 
print("Tingkat Akurasi :%d persen"%(akurasi*100))

confusion matrix
[[241   0   0   0]
 [  0 576   0   0]
 [  0   0 402   0]
 [  0   0   0  19]]
tingkat akurasi algoritma C4.5
Akurasi :               precision    recall  f1-score   support

           0       1.00      1.00      1.00       241
           1       1.00      1.00      1.00       576
           2       1.00      1.00      1.00       402
           3       1.00      1.00      1.00        19

    accuracy                           1.00      1238
   macro avg       1.00      1.00      1.00      1238
weighted avg       1.00      1.00      1.00      1238

Tingkat Akurasi :100 persen


In [11]:
import graphviz
dot_data = tree.export_graphviz(model, out_file=None,filled = True)
graph = graphviz.Source(dot_data)
graph.view()

'Source.gv.pdf'